### ISSUE TITLE
In Hasmany attribute if i delete one and add a different record it is not throughing isDirty

### ISSUE THREAD

**Issue by Arunkumarvelu** [meszike123/ember-managed-relationships#2]
In isReferenceChanged method we check for length if length doen't matches it through it is dirty. 
If the length is same means it go inside any function it will check for 

(e === currentValue[i]) 

Here currentValue[i] is undefined because it is not an array. My assumption the logic should be

 (e !== currentValue.currentState[i])

Then it will work

**Comment by meszike123** [comment]
Hi sry for the late answer. Thank you very much for the bug report. 

Today I have updated the code and now this issue should be fixed
